version: "3"
services:
  es:
    image: elasticsearch:7.10.1
    container_name: es
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    

  web:
    image: dahbka/foodtrucks-web
    container_name: foodtrucks-web
    command: ./entrypoint.sh python3 ./app.py
    depends_on:
      - es
    ports:
      - 5000:5000